# Generated by Django 4.0.1 on 2022-02-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
